# 
# 1. ConfigMap with prometheus.yml
# 2. Deployment: 
# 3. Service as NodePort 30005
# 

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf
  namespace: dev
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-deployment
  template:
    metadata:
      labels:
        app: prometheus-deployment
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-conf
            defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: dev
spec:
  selector:
    app: prometheus-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
      nodePort: 30005

