apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: dev
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: ""
  MYSQL_USER: cGV0Y2xpbmlj # base 64
  MYSQL_PASSWORD: cGV0Y2xpbmlj
  MYSQL_DATABASE: cGV0Y2xpbmlj
