#
# This Runner installs K3s and Terraform
# 
# - Install sshpass on Runner
# - Install K3s on Server
# - Install Terraform on Server
# 

name: Deploy-DEV

on:
  push:
    branches: [dev-branch]
    paths:  # Only triggers on changes
      - .github/workflows/Deploy-Basic-Setup.yml
        
jobs:

  Job-1-Deploy-DEV:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code from the repository
      uses: actions/checkout@v3

    - name: Just to be sure
      run: |
        echo "checkout:"
        git checkout dev-branch
  
    - name: Install sshpass on Runner
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass


    - name: Install K3s on Server
      env:
        SSH_PASSWORD: ${{ secrets.SSH_ALEX_SERVER_PW }}
        SSH_HOST: ${{ secrets.SSH_ALEX_SERVER_IP }}
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -o LogLevel=ERROR ubuntu@$SSH_HOST << 'EOF'
          # PreTasks
          kubectl delete namespace dev --ignore-not-found
          sudo apt-get update -y
          sudo apt-get upgrade -y
          # Install K3s
          sudo apt-get install -y curl
          curl -sfL https://get.k3s.io | sh -
          mkdir -p ~/.kube
          sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
          sudo chown $USER:$USER ~/.kube/config
          sudo chmod 644 ~/.kube/config
          sudo chmod 644 /etc/rancher/k3s/k3s.yaml
          sudo chown ubuntu:ubuntu /etc/rancher/k3s/k3s.yaml
          # Create namespace
          kubectl create namespace dev
        EOF


    - name: Install Terraform on Server
      env:
        SSH_PASSWORD: ${{ secrets.SSH_ALEX_SERVER_PW }}
        SSH_HOST: ${{ secrets.SSH_ALEX_SERVER_IP }}
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -o LogLevel=ERROR ubuntu@$SSH_HOST << 'EOF'
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com focal main"
          sudo apt-get update
          sudo apt-get install -y terraform
          rm -r /home/ubuntu/petclinic-jul24-deploy
          mkdir /home/ubuntu/petclinic-jul24-deploy
        EOF
