#
# This Runner is to reset the server:
# 
#   - Install sshpass on Runner
#   - Reset (delete namespace) and install K3s
#   - Create Secret for AlertManager Slack API URL as YAML ("kubectl create secret" does base64 encoding urgh)
#   - Create Secret for Ingress SSL
#   - Reset ( delete & create) working directoy
# 

name: Server-BasicSetup

on:
  push:
    branches: [staging-branch]
    paths:  # Only triggers on changes of:
      - .github/workflows/Server-BasicSetup.yml

jobs:

  Job-1-Reset-and-install-BasicSetup:

    runs-on: ubuntu-latest
    
    steps:


    - name: Checkout code from the repository
      uses: actions/checkout@v3


    - name: Install sshpass on Runner
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass


    # Reset (delete namespace) and install K3s
    - name: Deploy K3s on server
      run: |
        echo "Deploying on server"
        sshpass -p "${{ secrets.SSH_ALEX_SERVER_PW }}" ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SSH_ALEX_SERVER_IP }} bash << 'EOF'
          # PreTasks
          kubectl delete namespace dev --ignore-not-found
          kubectl delete namespace staging --ignore-not-found
          sudo apt-get update -y
          sudo apt-get upgrade -y
          # Install K3s
          sudo apt-get install -y curl
          curl -sfL https://get.k3s.io | sh -
          mkdir -p ~/.kube
          sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
          sudo chown $USER:$USER ~/.kube/config
          sudo chmod 644 ~/.kube/config
          sudo chmod 644 /etc/rancher/k3s/k3s.yaml
          sudo chown ubuntu:ubuntu /etc/rancher/k3s/k3s.yaml
          # Create namespace
          kubectl create namespace staging
        EOF
        echo "K3s installed"
  

    # Create Secret for AlertManager Slack API URL as YAML ("kubectl create secret" does base64 encoding urgh)
    - name: Create ConfigMap Alertmanager
      env:
        SLACK_API_URL: ${{ secrets.ALERTMANAGER_URL_SLACK }}
        SSH_PASSWORD: ${{ secrets.SSH_ALEX_SERVER_PW }}
        SSH_HOST: ${{ secrets.SSH_ALEX_SERVER_IP }}
      run: |
        # Transfer the ConfigMap file to the server
        sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -r monitoring/pmth-almg-ConfigMap.yml ubuntu@$SSH_HOST:~/petclinic-jul24-deploy
        
        # Replace the placeholder with the secret value
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no ubuntu@$SSH_HOST bash << EOF
          # Use sed to replace the REPL_SLACK_API_URL placeholder with the actual SLACK_API_URL value
          sed -i "s|REPL_SLACK_API_URL|$SLACK_API_URL|g" ~/petclinic-jul24-deploy/pmth-almg-ConfigMap.yml
          # apply the configmap
          kubectl apply -f /home/ubuntu/petclinic-jul24-deploy/pmth-almg-ConfigMap.yml
        EOF
      

    # Create Secret for Ingress SSL
    - name: Create TLS Secret 
      env:
        K8S_TLS_KEY: ${{ secrets.SSL_INGRESS_SIMPLYSTU_KEY }}
        K8S_TLS_CERT: ${{ secrets.SSL_INGRESS_SIMPLYSTU_CERT }}
        SSH_PASSWORD: ${{ secrets.SSH_ALEX_SERVER_PW }}
        SSH_HOST: ${{ secrets.SSH_ALEX_SERVER_IP }}
      run: |
        # Use sshpass to login and run code
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no \
          ubuntu@$SSH_HOST << EOF
            # create files
            echo "$K8S_TLS_KEY" > tls.key
            echo "$K8S_TLS_CERT" > tls.crt
            # create secret
            kubectl create secret tls petclinic-tls \
              --cert=tls.crt \
              --key=tls.key \
              --namespace=staging
            # delete files
            rm tls.key tls.crt
        EOF

    # Reset working directoy
    - name: Reset working directoy
      run: |
        sshpass -p "${{ secrets.SSH_ALEX_SERVER_PW }}" ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SSH_ALEX_SERVER_IP }} bash << 'EOF'
          # delete working-directory
          rm -r /home/ubuntu/petclinic-jul24-deploy
          # create working-directory
          mkdir -p /home/ubuntu/petclinic-jul24-deploy
        EOF


# Server from scratch installation needed:
# - docker
# - stress
# - 
