apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configmap
  namespace: monitoring
data:
  prometheus.yml: |-
    apiVersion: 1
    datasources:
      - access: proxy
        editable: true
        name: prometheus
        orgId: 1
        type: prometheus
        url: http://prometheus-service.monitoring.svc:8080
        version: 1
  sample-dashboard.json: |
    {
      "annotations": {
        "list": []
      },
      "panels": [
        {
          "datasource": "Prometheus",
          "id": 1,
          "targets": [
            {
              "expr": "sum(rate(http_requests_total[5m]))",
              "legendFormat": "{{method}} {{status}}",
              "refId": "A"
            }
          ],
          "type": "graph"
        }
      ],
      "schemaVersion": 16,
      "title": "Sample Dashboard",
      "version": 1
    }
