apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configmap
data:
  dashboard.json: |
    {
      "dashboard": {
        "title": "Simple Dashboard",
        "panels": [
          {
            "type": "graph",
            "title": "Sample Graph",
            "targets": [
              {
                "target": "sample.metric"
              }
            ],
            "xaxis": {
              "mode": "time"
            },
            "yaxes": [
              {
                "format": "short"
              }
            ]
          }
        ],
        "schemaVersion": 26,
        "version": 1
      }
    }
