# 
# 1. Deployment
# 2. Service as NodePort: 32000
# 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - name: grafana
          containerPort: 3000
        resources:
          limits:
            memory: "1Gi"
            cpu: "400m"
          requests: 
            memory: 500M
            cpu: "200m"
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-storage
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-configmap
            readOnly: true  # Ensure it is read-only
          - mountPath: /var/lib/grafana/dashboards
            name: grafana-configmap
            readOnly: true  # This is the path for dashboards
        env:  # Add this section to set the environment variables
          - name: GF_DASHBOARDS_JSON_ENABLED
            value: "true"
          - name: GF_DASHBOARDS_JSON_PATH
            value: "/var/lib/grafana/dashboards"
      volumes:
        - name: grafana-storage
          emptyDir: {}  # Change this to a PVC if you need persistent storage
        - name: grafana-configmap
          configMap:
            name: grafana-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '3000'
spec:
  selector: 
    app: grafana
  type: NodePort  
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000
---