apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configmap
  namespace: monitoring
data:
  grafana.ini: |
    [alerting]
    enabled = true

  # Alert rules go in a separate YAML file
  alert-rules.yaml: |
    apiVersion: 1
    groups:
      - orgId: 1
        name: Alerts-Server-CPU
        folder: Folder-Alerts-Server
        interval: 5s
        rules:
          - alert: HighCPUUsage
            expr: avg(node_cpu_seconds_total{mode="idle"}) < 20
            for: 5m
            labels:
              severity: critical
            annotations:
              title: "High CPU Usage Alert"  # Added title
              summary: "High CPU Usage"
              description: "CPU usage is above 80% for more than 5 minutes."
            dashboardUid: rYdddlPWk
            panelId: 77
            noDataState: NoData
            execErrState: Error
            isPaused: false
            notification_settings:
              receiver: grafana-to-Slack

  # Contact points go in a separate YAML file
  contact-points.yaml: |
    apiVersion: 1
    receivers:
      - orgId: 1
        name: grafana-to-Slack
        type: slack  # Correctly define the receiver type at the receiver level
        settings:
          url: https://hooks.slack.com/services/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
        disableResolveMessage: false
