apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configmap
  namespace: monitoring
data:
  prometheus.yaml: |-
    apiVersion: 1
    datasources:
      - name: "prometheus"
        type: "prometheus"
        access: "proxy"
        url: "http://prometheus-service.monitoring.svc:8080"
        isDefault: true
        editable: true
        version: 1
  grafana.ini: |
    [smtp]
    enabled = true
    host = smtp.gmail.com:587
    user = Alex Stu
    password = StuAl777!
    skip_verify = false
    from_address = simplyalexstu@gmail.com
    from_name = Grafana Alerts
    ehlo_identity = grafana.local