# 
# 1. Deployment
# 2. Service as NodePort: 32000
# kubectl describe deployment grafana-deployment -n monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: monitoring
spec:
  replicas: 1  # Specify the number of replicas you want
  selector:  # Add this field to define the selector
    matchLabels:
      app: grafana  # This should match the labels in the pod template
  template:
    metadata:
      labels:  # Add labels here to match the selector
        app: grafana
    spec:
      volumes:
        - name: dashboards
          configMap:
            name: grafana-dashboards  # The name of the ConfigMap
      containers:
        - name: grafana
          image: grafana/grafana:latest
          volumeMounts:
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards  # The path where Grafana looks for dashboards
          env:
            - name: GF_DASHBOARDS_JSON_ENABLED
              value: "true"
            - name: GF_DASHBOARDS_JSON_PATH
              value: "/var/lib/grafana/dashboards/*.json"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '3000'
spec:
  selector: 
    app: grafana
  type: NodePort  
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000
---