apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configmap
  namespace: monitoring
data:
  prometheus.yaml: |-
    apiVersion: 1
    datasources:
      - name: "prometheus"
        type: "prometheus"
        access: "proxy"
        url: "http://prometheus-service.monitoring.svc:8080"
        isDefault: true
        editable: true
        version: 1
