apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configmap
  namespace: monitoring
  labels:
    grafana_configmap: "1"
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
               "access":"proxy",
                "editable": true,
                "name": "prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prometheus-service.monitoring.svc:8080",
                "version": 1
            }
        ]
    }

#  grafana.ini: |
    # [auth.anonymous]
    # # enable anonymous access
    # enabled = true
    # # specify organization name that should be used for unauthenticated users
    # org_name = ORGANIZATION
    # [auth.anonymous]
    # enabled = true
    # org_role = Admin
    # [auth.basic]
    # enabled = false
    # [auth]
    # disable_login_form = true
    # [security]
    # admin_user = admin
    # admin_password = admin
    # [auth.anonymous]
    # enabled = true
    # org_name = Main Org.
    # org_role = Viewer


  # Add the dashboard providers config to point to the mounted dashboard folder
  dashboardProviders.yaml: |-
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards

  # Add the dashboard JSON content here
  dashboard.json: |-
    {
        "datasource": {
          "default": false,
          "type": "prometheus",
          "uid": "P1809F7CD0C75ACF3"
        },
        "fieldConfig": {
          "defaults": {
            "custom": {
              "drawStyle": "line",
              "lineInterpolation": "linear",
              "barAlignment": 0,
              "barWidthFactor": 0.6,
              "lineWidth": 1,
              "fillOpacity": 0,
              "gradientMode": "none",
              "spanNulls": false,
              "insertNulls": false,
              "showPoints": "auto",
              "pointSize": 5,
              "stacking": {
                "mode": "none",
                "group": "A"
              },
              "axisPlacement": "auto",
              "axisLabel": "",
              "axisColorMode": "text",
              "axisBorderShow": false,
              "scaleDistribution": {
                "type": "linear"
              },
              "axisCenteredZero": false,
              "hideFrom": {
                "tooltip": false,
                "viz": false,
                "legend": false
              },
              "thresholdsStyle": {
                "mode": "off"
              }
            },
            "color": {
              "mode": "palette-classic"
            },
            "mappings": [],
            "thresholds": {
              "mode": "absolute",
              "steps": [
                {
                  "color": "green",
                  "value": null
                },
                {
                  "color": "red",
                  "value": 80
                }
              ]
            }
          },
          "overrides": []
        },
        "gridPos": {
          "h": 8,
          "w": 12,
          "x": 0,
          "y": 0
        },
        "id": 1,
        "options": {
          "tooltip": {
            "mode": "single",
            "sort": "none"
          },
          "legend": {
            "showLegend": true,
            "displayMode": "list",
            "placement": "bottom",
            "calcs": []
          }
        },
        "targets": [
          {
            "datasource": {
              "type": "prometheus",
              "uid": "P1809F7CD0C75ACF3"
            },
            "editorMode": "builder",
            "expr": "100 - (max(irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
            "format": "time_series",
            "instant": false,
            "legendFormat": "__auto",
            "range": true,
            "refId": "A"
          }
        ],
        "title": "CPU Usage",
        "type": "timeseries"
      }










# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: grafana-datasources
#   namespace: monitoring
# data:
#   prometheus.yaml: |-
#     {
#         "apiVersion": 1,
#         "datasources": [
#             {
#                "access":"proxy",
#                 "editable": true,
#                 "name": "prometheus",
#                 "orgId": 1,
#                 "type": "prometheus",
#                 "url": "http://prometheus-service.monitoring.svc:8080",
#                 "version": 1
#             }
#         ]
#     }