---
kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: dev
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'

    # receivers:
    # - name: slack_demo
    #   slack_configs:
    #   - api_url: https://hooks.slack.com/services/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
    #     channel: '#cicd'
    receivers:
      - name: 'slack-receiver'
        slack_configs:
        - api_url: 'https://hooks.slack.com/services/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'
          channel: '#cicd'
          send_resolved: true

    route:
      receiver: 'slack-receiver'
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 2m
---