# 
# kubectl create -f config-map.yaml
# 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.rules: |-

  prometheus.yml: |-

---