kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-configmap
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
    receivers: