apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-configmap
  namespace: dev
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 10s
      slack_api_url: ''

    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 2h
      receiver: 'slack'

    receivers:
    - name: 'slack'
      slack_configs:
      - channel: '#cicd'
        text: 'Alert: {{ .CommonLabels.alertname }}\n{{ .CommonAnnotations.summary }}\n\nDetails: {{ .CommonAnnotations.description }}'
        send_resolved: true 
