---
kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: dev
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: slack_demo
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 1m
      routes:
        - receiver: slack_demo
          group_wait: 10s
          repeat_interval: 1m

    receivers:
    - name: slack_demo
      slack_configs:
      - api_url: https://hooks.slack.com/services/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
        channel: '#cicd'
