apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-configmap
  namespace: monitoring
data:
  config.yml: |-
    global:
      resolve_timeout: 5m
      
    route:
      receiver: 'slack-receiver'  # Updated to use the Slack receiver
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h

    receivers:
    - name: default-receiver  # Placeholder for other notifications
      # No slack_configs defined

    - name: slack-receiver
      slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: 'cicd'  # Change to your actual Slack channel
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
