# 
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
  namespace: dev
data:
  config.yml: |-
    route:
      receiver: slack
      group_by: ['alertname']
      group_wait: 10s
      repeat_interval: 2m
      routes:
        - receiver: slack
          match:
            severity: slack

    receivers:
    - name: slack
      slack_configs:
      - api_url: '{{ .Env.SLACK_API_URL }}'
---