kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
  namespace: dev
data:
  config.yml: |-
    global:

    route:
      receiver: slack
      group_by: ['alertname']
      group_wait: 10s
      repeat_interval: 3m
      routes:
        - receiver: slack
          match:
            severity: slack
          group_wait: 10s
          repeat_interval: 1m

    receivers:
    - name: slack
      slack_configs:
      - api_url: 
        channel: '#cicd'
