# Use the official Eclipse Temurin JDK 17 base image
FROM eclipse-temurin:17-jdk-jammy

# Set the working directory inside the container
WORKDIR /app

# Copy Maven wrapper and pom.xml files
COPY app/.mvn/ .mvn
COPY app/mvnw app/pom.xml ./

# Grant execute permissions to the Maven wrapper
RUN chmod +x mvnw

# Resolve the project dependencies
RUN app/mvnw dependency:resolve

# Copy the source code to the container
COPY app/src/ src

# Default command to run the Spring Boot application
CMD ["app/mvnw", "spring-boot:run"]

# Command to build docker-image:
# docker build -t jul24-petclinic-image -f dockerfile-app.yml .
# docker images
# docker tag jul24-petclinic-image alexstue/jul24-petclinic:1.0
# docker push alexstue/jul24-petclinic:1.0

