apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petclinic-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: "traefik"
    # traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    # traefik.ingress.kubernetes.io/tls: "true"  # Enabling TLS
    # traefik.ingress.kubernetes.io/tls.secret: "petclinic-secret-tls"  # Referencing your existing TLS secret
spec:
  # tls:
  # - hosts:
  #   - petclinic.dst-jul24.cloudns.be
  #   secretName: petclinic-secret-tls  # Name of the TLS secret
  rules:
  - host: petclinic.dst-jul24.cloudns.be
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: petclinic-service
            port:
              number: 8080
---