# Use the official Eclipse Temurin JDK 17 base image
FROM eclipse-temurin:17-jdk-jammy

# Set the working directory inside the container
WORKDIR /app

# Copy Maven wrapper and pom.xml files
COPY .mvn/ .mvn
COPY mvnw ./
COPY pom.xml ./

# Grant execute permissions to the Maven wrapper
RUN chmod +x mvnw && chmod +x .mvn/wrapper/*

# Resolve the project dependencies
RUN ./mvnw dependency:resolve

# Copy the source code to the container
COPY src/ src

# Default command to run the Spring Boot application
CMD ["./mvnw", "spring-boot:run"]
