# 
# 1. Deployment
# 2. Service as LoadBalancer for ingress
# 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: alexstue/jul24-petclinic:latest

        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/petclinic
        - name: SPRING_DATASOURCE_USERNAME
          value: petclinic
        - name: SPRING_DATASOURCE_PASSWORD
          value: petclinicpassword

        resources:
          requests:
            memory: 200Mi
            cpu: 200m
          limits:
            memory: 400Mi
            cpu: 300m
        ports:
        - containerPort: 8080 
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  namespace: dev
spec:
  selector:
    app: petclinic
  type: LoadBalancer # NodePort also optional
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001 # 30002 on NodePort Version
---