# 
# 1. PersistentVolume
# 2. StatefulSet
# 3. Service
# 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqlserver-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqlserver
  template:
    metadata:
      labels:
        app: mysqlserver
    spec:
      containers:
        - name: mysqlserver
          image: mysql/mysql-server:8.0
          ports:
            - containerPort: 3306

          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 200Mi
              cpu: 200m

          env:
            - name: MYSQL_ROOT_PASSWORD
              value: ""
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
            - name: MYSQL_USER
              value: "petclinic"
            - name: MYSQL_PASSWORD
              value: "petclinic"
            - name: MYSQL_DATABASE
              value: "petclinic"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-config
              mountPath: /etc/mysql/conf.d
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-pvc
        - name: mysql-config
          persistentVolumeClaim:
            claimName: mysql-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysqlserver-service
  namespace: dev
spec:
  selector:
    app: mysqlserver
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
---