# service2.yml
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro2-deployment
  labels:
    app: micro2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: micro2
  template:
    metadata:
      labels:
        app: micro2
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.10
        ports:
        - containerPort: 8080
---
# service 
apiVersion: v1
kind: Service
metadata:
  name: lb-service-2
spec:
  selector:
    app: micro2
  ports:
  - port: 8080