# service1.yml
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro1-deployment
  labels:
    app: micro1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: micro1
  template:
    metadata:
      labels:
        app: micro1
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.10
        ports:
        - containerPort: 8080
---
# service 
apiVersion: v1
kind: Service
metadata:
  name: lb-service-1
spec:
  selector:
    app: micro1
  ports:
  - port: 8080