# 
# 1. Deployment
# 2. Service as NodePort: 31000
# 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:latest
        args:
          - "--config.file=/etc/alertmanager/alertmanager.yml"
          - "--storage.path=/alertmanager"
        ports:
        - name: alertmanager
          containerPort: 9093
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
          limits:
            cpu: 40m
            memory: 100Mi
        volumeMounts:
        - name: alertmanager-config-volume
          mountPath: /etc/alertmanager

      volumes:
      - name: alertmanager-config-volume
        configMap:
          name: alertmanager-config
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
  namespace: dev
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9093'
spec:
  selector: 
    app: alertmanager
  type: NodePort  
  ports:
    - port: 9093
      targetPort: 9093
      nodePort: 31000

---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
  namespace: dev
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9093'
spec:
  selector: 
    app: alertmanager
  type: NodePort  
  ports:
    - port: 9093
      targetPort: 9093
      nodePort: 31000
---
