name: Deploy lates images on DTS via Terraform apply

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout code from the repository
      uses: actions/checkout@v3

    # Step 4: Extract the server IP
    - name: Extract Server IP
      id: extract_ip
      run: |
        SERVER_IP=$(grep -A 3 -E '^variable "server_ip_tf"' infra/terraform/variables.tf | grep 'default' | sed -n 's/.*default *= *"\([^"]*\)".*/\1/p')
        echo "SERVER_IP=${SERVER_IP}"
        echo "##[set-output name=server_ip;]${SERVER_IP}"
        echo "Extracted Server IP: ${SERVER_IP}"
    
    # Step 5: Set up SSH with the private key
    - name: Set up SSH with private-key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ steps.extract_ip.outputs.server_ip }} >> ~/.ssh/known_hosts
        echo "Server IP is: ${{ steps.extract_ip.outputs.server_ip }}"
        echo "Known hosts:"
        cat ~/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_DTS_PRIVATE_KEY }}

    - name: Copy script to server
      run: |
        echo "Copy script to server with IP: ${SERVER_IP}"
        scp -o StrictHostKeyChecking=no infra/scripts/deploy-on-dts.sh ubuntu@${{ steps.extract_ip.outputs.server_ip }}:/home/ubuntu/

    - name: Run script via SSH
      run: |
        SERVER_IP=${{ steps.extract_ip.outputs.server_ip }}
        echo "Deploying to server with IP: $SERVER_IP"
        ssh -o StrictHostKeyChecking=no ubuntu@$SERVER_IP << 'EOF'
          chmod +x /home/ubuntu/deploy-on-dts.sh
          /home/ubuntu/deploy-on-dts.sh
        EOF
