#
# This Runner deploys or update the staging-infrastucture on a server
# 
#   - Just to be sure (sets used repo on runner to staging-branch)
#   - Install sshpass
#   - Copy Manifests to Server
#   - Run Manifest on Server
# 

name: Deploy-Staging

on:
  push:
    branches: [staging-branch]
    paths:  # Only triggers on changes
      - 'infra/**'
      - 'monitoring/**'
      - .github/workflows/Deploy-DEV.yml
        
jobs:

  Job-1-Deploy-Staging:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Just to be sure
        run: |
          echo "checkout:"
          git checkout staging-branch


      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass


      - name: Copy Manifests to Server
        env:
          SSH_PASSWORD: ${{ secrets.SSH_ALEX_SERVER_PW }}
          SSH_HOST: ${{ secrets.SSH_ALEX_SERVER_IP }}
        run: |
          echo "Configmaps: Monitoring"
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -r monitoring/* ubuntu@$SSH_HOST:~/petclinic-jul24-deploy
          echo "Manifests: App, Ingress, NodeExporter, Promeutheus, AlertManager, Grafana"
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -r infra/k3s/8-App-mon-ingr/* ubuntu@$SSH_HOST:~/petclinic-jul24-deploy


      - name: Run Manifest on Server
        env:
          SSH_PASSWORD: ${{ secrets.SSH_ALEX_SERVER_PW }}
          SSH_HOST: ${{ secrets.SSH_ALEX_SERVER_IP }}
        run: |
          echo "Apply the manifests"
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no \
            ubuntu@$SSH_HOST << 'EOF'
              # Configs
              kubectl apply -f /home/ubuntu/petclinic-jul24-deploy/mon-pmth-ClusterRole.yml
              kubectl apply -f /home/ubuntu/petclinic-jul24-deploy/pmth-svr-ConfigMap.yml
              kubectl apply -f /home/ubuntu/petclinic-jul24-deploy/grfa-ConfigMap.yml
              # pmth-almg-ConfigMap.yml already active
              # Deployments
              kubectl apply -f /home/ubuntu/petclinic-jul24-deploy/app-combined.yml
              kubectl apply -f /home/ubuntu/petclinic-jul24-deploy/ingress-resource.yml
              kubectl apply -f /home/ubuntu/petclinic-jul24-deploy/mon-pmth-exp-NodeExporter.yml
              kubectl apply -f /home/ubuntu/petclinic-jul24-deploy/mon-pmth-svr-comb.yml
              kubectl apply -f /home/ubuntu/petclinic-jul24-deploy/mon-pmth-almg-comb.yml
              kubectl apply -f /home/ubuntu/petclinic-jul24-deploy/mon-grfa-comb.yml
          EOF
