#
# This Runner is to compile the app to an docker-image and upload the image to Docker-Hub
# In DEV-environment (namespace)
#

name: Docker-Build and Push Docker Image to DockerHub

on:
  push:
    branches:
      - dev-branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build the Docker image using Docker Compose
      - name: Build the Docker image with Docker Compose
        env:
          DOCKERHUB_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/jul24-petclinic:latest
        run: |
          docker-compose -f app/docker-compose.yml build

      # Push the Docker image to DockerHub
      - name: Push the Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/jul24-petclinic:latest