name: Terraform Plan and Apply

on:
  push:
    branches: [dev-branch]
    paths:
      - .github/workflows/Terraform-apply.yml

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.8  # Ensure this is your desired version

      - name: Terraform Login
        env:
          TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
        run: echo $TFC_TOKEN | terraform login

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve
