name: Terraform Plan and Apply

on:
  push:
    branches: [dev-branch]
    paths:
      - .github/workflows/Terraform-apply.yml

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.8  # Ensure this is your desired version

      - name: Terraform Init
        env:
          TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
        run: |
          # Create a credentials file for Terraform
          mkdir -p ~/.terraform.d
          echo "{\"credentials\":{\"app.terraform.io\":{\"token\":\"$TFC_TOKEN\"}}}" > ~/.terraform.d/credentials.tfrc.json
          terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve
