name: Terraform Plan and Apply

on:
  push:
    branches: [dev-branch]
    paths:
      - .github/workflows/Terraform-apply.yml

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.8

      - name: Terraform Init
        env:
          TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
          TFC_ORG: ${{ secrets.TFC_ORG }}
          TFC_WORKSPACE: ${{ secrets.TFC_WORKSPACE }}
        run: |
          terraform login -token=$TFC_TOKEN
          terraform init

      - name: Terraform Plan
        env:
          TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
          TFC_ORG: ${{ secrets.TFC_ORG }}
          TFC_WORKSPACE: ${{ secrets.TFC_WORKSPACE }}
        run: |
          terraform plan

      - name: Terraform Apply
        # if: github.event_name == 'push'
        env:
          TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
          TFC_ORG: ${{ secrets.TFC_ORG }}
          TFC_WORKSPACE: ${{ secrets.TFC_WORKSPACE }}
        run: |
          terraform apply -auto-approve
