# 
# ...
# 
# 

name: Terraform Plan and Apply

on:
  push:
    branches: [dev-branch]
    paths:
      - .github/workflows/Terraform-apply.yml

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.8  # Specify your desired version

      - name: Create Terraform Credentials File
        env:
          TFC_TOKEN: ${{ secrets.TFC_TOKEN }}  # GitHub secret for your Terraform Cloud token
        run: |
          # Create the necessary directory
          mkdir -p ~/.terraform.d

          # Create the credentials file with the token
          echo "{\"credentials\":{\"app.terraform.io\":{\"token\":\"$TFC_TOKEN\"}}}" > ~/.terraform.d/credentials.tfrc.json

      - name: Terraform Init
        run: |
          cd infra/terraform
          terraform init

      - name: Terraform Plan
        run: |
          cd infra/terraform
          terraform plan

      - name: Terraform Apply
        #if: github.event_name == 'push'
        run: 
          cd infra/terraform
          terraform apply -auto-approve
